#! /usr/bin/env python3
# @file         js-test-runner
#               A simple test driver for peter-jr that runs JS code via PythonMonkey.require
# @author       Wes Garland, wes@distributive.network
# @date         Jun 2023
 
import sys, os
sys.path.append(os.path.dirname(__file__) + '/python') # location of pythonmonkey module
import pythonmonkey as pm

# Main
require = pm.createRequire(__file__)
require('console');

testName = os.path.realpath(sys.argv[1]);
testDir = os.path.dirname(testName);
pm.createRequire(testName)(testName);
